version: '3.8'

services:
  app:
    image: blog_front_prod
    build:
      context: ./blog_frontend
      dockerfile: Dockerfile
    environment:
      - PORT=3000
    container_name: blog_front_prod

  server:
    image: blog_back_prod
    build:
      context: ./blog_backend
      dockerfile: Dockerfile
    env_file:
      - ./blog_backend/.env
    container_name: blog_back_prod

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: blog_reverse-proxy_prod
    depends_on:
      - app
      - server
